apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: filebeat
  name: filebeat
  namespace: logging
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'filebeat:7.2.0'
  source:
    type: Git
    git: 
      uri: "https://github.com/mk811/logging-openshift-4.X.git"
      ref: "master"
    contextDir: filebeat
  strategy:
    type: Docker

---
apiVersion: v1
kind: ImageStream
metadata: 
  name: filebeat
  labels:
    app: filebeat