apiVersion: v1
kind: Template
metadata:
  name: filebeat-conf
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: filebeat-conf
      label:
        kubernetes.io/cluster-service: "true"
    data:
      filebeat.yml: |-
        filebeat.inputs:
          # - type: container
          #   paths:
          #     - /var/log/pods/*/*/*.log
          #   processors:
          #     - dissect:
          #         tokenizer: "/var/log/pods/%{k8s.podRaw}/%{k8s.container}/%{k8s.logIndex}.log"
          #         field: "log.file.path"


                
        #   - type: log
        #     paths:
        #       - /var/log/pods/*/*/*.log
        #     processors:
        #       - dissect:
        #         tokenizer: "/var/log/pods/%{kubernetes.pod.uid}/%{kubernestes.container.name}/%{index}.log"
        #         field: "source"
        #       - add_kubernetes_metadata:
        #         indexers:
        #           - pod_uid:
        #         matchers:
        #           - fields:
        #               lookup_fields: ["kubernetes.pod.uid"]

        # filebeat.inputs:
        #   - type: log
        #     paths:
        #       - /var/log/pods/*/*/*.log
        #     processors:
        #       - dissect:
        #           tokenizer: "/var/log/pods/%{k8s.podRaw}/%{k8s.container}/%{k8s.logIndex}.log"
        #           field: "log.file.path"

        filebeat.autodiscover:
          providers:
            - type: kubernetes
              host: ${NODE_NAME}
              in_cluster: true
              include_pod_uid: true
              include_annotations: '*'
              hints.enabled: true
              hints.default_config.enabled: false
              templates:
                - condition.regexp:
                    kubernetes.namespace: 'default'
                  config:
                    - type: container
                      combine_partial: true
                      cri.parse_flags: true
                      cri.force: true
                      paths:
                        - "/var/log/pods/${data.kubernetes.namespace}_${data.kubernetes.pod.name}_${data.kubernetes.pod.uid}/${data.kubernetes.container.name}/*.log"
                  

        # filebeat.autodiscover:
        #   providers:
        #   - type: kubernetes
        #     include_pod_uid: true
        #     in_cluster: true
        #     hints.enabled: true
        #     include_annotations: '*'
        #     templates:
        #       - condition.regexp:
        #           kubernetes.container.name: '.+'
        #         config:
        #           - type: container
        #             combine_partial: true
        #             cri.parse_flags: true
        #             cri.force: true
        #             paths: 
        #               - "/var/log/pods/${data.kubernetes.namespace}_${data.kubernetes.pod.name}_${data.kubernetes.pod.uid}/${data.kubernetes.container.name}/*.log"

            # - type: kubernetes
            #   # host: ${NODE_NAME}
            #   # include_pod_uid: true
            #   # in_cluster: true
            #   # include_annotations: '*'
            #   hints.enabled: true
            #   hints.default_config:
            #     type: container
            #     # combine_partial: true
            #     # cri.parse_flags: true
            #     # cri.force: true
            #     paths:
            #     - "/var/log/pods/${data.kubernetes.namespace}_${data.kubernetes.pod.name}_${data.kubernetes.pod.uid}/${data.kubernetes.container.name}/*.log"

        #================================ General =====================================

        # The name of the shipper that publishes the network data. It can be used to group
        # all the transactions sent by a single shipper in the web interface.
        name: ${POD_NAME}

        # Optional fields that you can specify to add additional information to the
        # output.
        fields:
          env: poc

        #----------------------------- Logstash output --------------------------------
        output.logstash:
          # The Logstash hosts
          hosts: ["${LOGSTASH_ENDPOINT}:5044"]

        #================================ Processors =====================================
        processors:
          - add_host_metadata: ~
          - add_cloud_metadata: ~


        #================================ Logging =====================================
        # Available log levels are: error, warning, info, debug
        logging.level: debug

parameters:
  - description: Logstash HTTP Post Endpoint
    displayName: Logstash HTTP Post Endpoint
    name: LOGSTASH_ENDPOINT
    required: true
