apiVersion: v1
kind: Template
metadata:
  name: filebeat-conf
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: filebeat-conf
    data:
      filebeat.yml: |-
        filebeat.autodiscover:
          providers:
            - type: kubernetes
              include_pod_uid: true
              in_cluster: true
              hints.enabled: true
              include_annotations: '*'
              templates:
                - condition:
                    regexp:
                      kubernetes.container.name: '.+'
                  config:
                    - type: container
                      combine_partial: true
                      cri.parse_flags: true
                      cri.force: true
                      paths: 
                        - "/var/log/pods/${data.kubernetes.namespace}_${data.kubernetes.pod.name}_${data.kubernetes.pod.uid}/${data.kubernetes.container.name}/*.log"

        #============================= Filebeat modules ===============================

        filebeat.config.modules:
          # Glob pattern for configuration loading
          path: ${path.config}/modules.d/*.yml
          reload.enabled: false

        #================================ General =====================================

        # The name of the shipper that publishes the network data. It can be used to group
        # all the transactions sent by a single shipper in the web interface.
        name: ${POD_NAME}

        # Optional fields that you can specify to add additional information to the
        # output.
        fields:
          env: poc

        #----------------------------- Logstash output --------------------------------
        output.logstash:
          # The Logstash hosts
          hosts: ["${LOGSTASH_ENDPOINT}:5044"]

        #================================ Processors =====================================
        processors:
          - add_host_metadata: ~
          - add_cloud_metadata: ~
          - add_kubernetes_metadata: ~

        #================================ Logging =====================================
        # Available log levels are: error, warning, info, debug
        logging.level: error

parameters:
  - description: Logstash HTTP Post Endpoint
    displayName: Logstash HTTP Post Endpoint
    name: LOGSTASH_ENDPOINT
    required: true
