apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      name: filebeat
  template:
    metadata:
      labels:
        name: filebeat
        app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      # hostNetwork: true
      dnsPolicy: ClusterFirst

      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.4.2
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: filebeat-conf
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
            # - name: kube
            #   mountPath: /usr/share/.kube
            #   readOnly: true
            - name: data
              mountPath: /usr/share/filebeat/data
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: filebeat-conf
          configMap:
            name: filebeat-conf
        # - name: kube
        #   hostPath:
        #     path: /root/.kube
        - name: varlog
          hostPath:
            path: /var/log
        # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
