apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      name: filebeat
  template:
    metadata:
      labels:
        name: filebeat
        app: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
      - name: filebeat
        image: elastic/filebeat:7.4.2
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: filebeat-conf
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filebeat-conf
        configMap:
          name: filebeat-conf
      - name: varlog
        hostPath:
          path: /var/log