---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  project: logging

---
apiVersion: v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    app: filebeat
    project: logging
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"


---
kind: ClusterRoleBinding
apiVersion: v1
metadata:
  name: filebeat
  labels:
    app: filebeat
    project: logging
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: ""